/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonagemIdRouteImport } from './routes/personagem.$id'
import { Route as AuthenticatedMeuPersonagemRouteImport } from './routes/_authenticated/meu-personagem'
import { Route as AuthenticatedMestreRouteImport } from './routes/_authenticated/mestre'
import { Route as AuthenticatedMesaRouteImport } from './routes/_authenticated/mesa'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagemIdRoute = PersonagemIdRouteImport.update({
  id: '/personagem/$id',
  path: '/personagem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeuPersonagemRoute =
  AuthenticatedMeuPersonagemRouteImport.update({
    id: '/meu-personagem',
    path: '/meu-personagem',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMestreRoute = AuthenticatedMestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesaRoute = AuthenticatedMesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mesa': typeof AuthenticatedMesaRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/meu-personagem': typeof AuthenticatedMeuPersonagemRoute
  '/personagem/$id': typeof PersonagemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mesa': typeof AuthenticatedMesaRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/meu-personagem': typeof AuthenticatedMeuPersonagemRoute
  '/personagem/$id': typeof PersonagemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/mesa': typeof AuthenticatedMesaRoute
  '/_authenticated/mestre': typeof AuthenticatedMestreRoute
  '/_authenticated/meu-personagem': typeof AuthenticatedMeuPersonagemRoute
  '/personagem/$id': typeof PersonagemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/mesa' | '/mestre' | '/meu-personagem' | '/personagem/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/mesa' | '/mestre' | '/meu-personagem' | '/personagem/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/mesa'
    | '/_authenticated/mestre'
    | '/_authenticated/meu-personagem'
    | '/personagem/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PersonagemIdRoute: typeof PersonagemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagem/$id': {
      id: '/personagem/$id'
      path: '/personagem/$id'
      fullPath: '/personagem/$id'
      preLoaderRoute: typeof PersonagemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meu-personagem': {
      id: '/_authenticated/meu-personagem'
      path: '/meu-personagem'
      fullPath: '/meu-personagem'
      preLoaderRoute: typeof AuthenticatedMeuPersonagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mestre': {
      id: '/_authenticated/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof AuthenticatedMestreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesa': {
      id: '/_authenticated/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof AuthenticatedMesaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMesaRoute: typeof AuthenticatedMesaRoute
  AuthenticatedMestreRoute: typeof AuthenticatedMestreRoute
  AuthenticatedMeuPersonagemRoute: typeof AuthenticatedMeuPersonagemRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMesaRoute: AuthenticatedMesaRoute,
  AuthenticatedMestreRoute: AuthenticatedMestreRoute,
  AuthenticatedMeuPersonagemRoute: AuthenticatedMeuPersonagemRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PersonagemIdRoute: PersonagemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
